name: ${PROJECT}
networks:
  default:
    name: ${PROJECT}
    driver: bridge
services:
  wp:
    #image: soulteary/sqlite-wordpress:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT}
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./app:/var/www/html/wp-content
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini 
      - ./logs:/var/log
    ports:
      - 8080:80

